using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Numerics;
using System.Threading;
using System.Threading.Tasks;

namespace Zamane;

/// <summary>
/// HTTP client for KamuSM's Zamane timestamp service. Posts a
/// <c>TimeStampReq</c> to the configured base URL together with an
/// <c>identity</c> header generated by <see cref="IdentityGenerator"/>.
/// </summary>
/// <remarks>
/// Request flow:
/// <list type="number">
/// <item>
/// The <c>messageImprint.hashedMessage</c> is extracted from the
/// supplied <c>TimeStampReq</c>.
/// </item>
/// <item>
/// A hex-encoded identity is built from
/// <c>customerNo + password + hashedMessage</c> via
/// <see cref="IdentityGenerator.CreateIdentity"/>.
/// </item>
/// <item>
/// An HTTP POST is issued against the base URL with the identity set
/// on the <c>identity</c> header and the request body containing the
/// <c>TimeStampReq</c> DER bytes. The <c>Content-Type</c> header is
/// set to <c>application/timestamp-query</c>.
/// </item>
/// <item>
/// On success, the server replies with the DER-encoded
/// <c>TimeStampResp</c> (<c>application/timestamp-reply</c>), which is
/// returned to the caller.
/// </item>
/// </list>
/// </remarks>
public sealed class TimeStampClient
{
    /// <summary>
    /// Base URL of the KamuSM Zamane production timestamp server.
    /// </summary>
    public const string ProductionBaseUrl = "http://zd.kamusm.gov.tr";

    /// <summary>
    /// Base URL of the KamuSM Zamane test timestamp server.
    /// </summary>
    public const string TestBaseUrl = "http://tzd.kamusm.gov.tr";

    private const string TimeStampQueryMediaType = "application/timestamp-query";
    private const string IdentityHeaderName = "identity";

    private readonly HttpClient _httpClient;
    private readonly Uri _baseUrl;

    /// <summary>
    /// Initializes a new instance of the <see cref="TimeStampClient"/>
    /// class.
    /// </summary>
    /// <param name="baseUrl">
    /// Base URL of the Zamane timestamp server. See
    /// <see cref="ProductionBaseUrl"/> and <see cref="TestBaseUrl"/>.
    /// </param>
    /// <param name="httpClient">
    /// The <see cref="HttpClient"/> to use. When omitted, a new
    /// instance is created internally. In typical use, sharing an
    /// <see cref="HttpClient"/> via dependency injection is recommended.
    /// </param>
    public TimeStampClient(string baseUrl, HttpClient? httpClient = null)
        : this(new Uri(baseUrl, UriKind.Absolute), httpClient)
    {
    }

    /// <inheritdoc cref="TimeStampClient(string, HttpClient?)"/>
    public TimeStampClient(Uri baseUrl, HttpClient? httpClient = null)
    {
        _baseUrl = baseUrl;
        _httpClient = httpClient ?? new HttpClient();
    }

    /// <summary>
    /// Sends a timestamp request to the Zamane server and returns the
    /// DER-encoded <c>TimeStampResp</c> bytes.
    /// </summary>
    /// <param name="customerNo">
    /// KamuSM customer number, as a decimal string.
    /// </param>
    /// <param name="password">KamuSM customer password.</param>
    /// <param name="timeStampReq">
    /// The DER-encoded RFC 3161 <c>TimeStampReq</c>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token used to cancel the operation.
    /// </param>
    /// <returns>The DER-encoded <c>TimeStampResp</c> bytes.</returns>
    /// <exception cref="HttpRequestException">
    /// Thrown when the server returns a non-success HTTP status code.
    /// </exception>
    public Task<byte[]> RequestTimestampAsync(
        string customerNo,
        string password,
        byte[] timeStampReq,
        CancellationToken cancellationToken = default)
    {
        return RequestTimestampAsync(
            BigInteger.Parse(customerNo, System.Globalization.CultureInfo.InvariantCulture),
            password,
            timeStampReq,
            cancellationToken);
    }

    /// <inheritdoc cref="RequestTimestampAsync(string, string, byte[], CancellationToken)"/>
    public async Task<byte[]> RequestTimestampAsync(
        BigInteger customerNo,
        string password,
        byte[] timeStampReq,
        CancellationToken cancellationToken = default)
    {
        var hashedMessage = TimeStampRequestParser.GetHashedMessage(timeStampReq);
        var identity = IdentityGenerator.CreateIdentity(customerNo, password, hashedMessage);

        using var request = new HttpRequestMessage(HttpMethod.Post, _baseUrl);
        request.Content = new ByteArrayContent(timeStampReq);
        request.Content.Headers.ContentType = new MediaTypeHeaderValue(TimeStampQueryMediaType);
        request.Headers.Add(IdentityHeaderName, identity);

        using var response = await _httpClient
            .SendAsync(request, HttpCompletionOption.ResponseContentRead, cancellationToken)
            .ConfigureAwait(false);

        if (!response.IsSuccessStatusCode)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var body = await response.Content
                .ReadAsStringAsync()
                .ConfigureAwait(false);

            throw new HttpRequestException(
                $"Zamane timestamp request failed: {(int)response.StatusCode} {response.ReasonPhrase}. Body: {body}");
        }

        cancellationToken.ThrowIfCancellationRequested();

        return await response.Content
            .ReadAsByteArrayAsync()
            .ConfigureAwait(false);
    }

    /// <summary>
    /// Sends a timestamp request to the Zamane server synchronously and
    /// returns the DER-encoded <c>TimeStampResp</c> bytes.
    /// </summary>
    /// <param name="customerNo">
    /// KamuSM customer number, as a decimal string.
    /// </param>
    /// <param name="password">KamuSM customer password.</param>
    /// <param name="timeStampReq">
    /// The DER-encoded RFC 3161 <c>TimeStampReq</c>.
    /// </param>
    /// <param name="cancellationToken">
    /// A token used to cancel the operation.
    /// </param>
    /// <returns>
    /// The DER-encoded <c>TimeStampResp</c> bytes.
    /// </returns>
    /// <remarks>
    /// This method blocks the calling thread until the timestamp response
    /// is received. For non-blocking I/O, use
    /// <see cref="RequestTimestampAsync(string,string,byte[],CancellationToken)"/>.
    /// </remarks>
    /// <exception cref="HttpRequestException">
    /// Thrown when the server returns a non-success HTTP status code.
    /// </exception>
    public byte[] RequestTimestamp(
        string customerNo,
        string password,
        byte[] timeStampReq,
        CancellationToken cancellationToken = default)
    {
        return RequestTimestampAsync(
                customerNo,
                password,
                timeStampReq,
                cancellationToken)
            .GetAwaiter()
            .GetResult();
    }

    /// <inheritdoc cref="RequestTimestamp(string,string,byte[],CancellationToken)"/>
    public byte[] RequestTimestamp(
        BigInteger customerNo,
        string password,
        byte[] timeStampReq,
        CancellationToken cancellationToken = default)
    {
        return RequestTimestampAsync(
                customerNo,
                password,
                timeStampReq,
                cancellationToken)
            .GetAwaiter()
            .GetResult();
    }
}